### ISSUE TITLE
The proposed city cannot be selected on the demo

### ISSUE THREAD

**Issue by plplmax** [travelpayouts/flights-api-project#11]
On your [demo](http://misc.travelpayouts.com/flights/), when you click on the suggested origin/destination city, the city is not selected.

**Comment by tpsupport** [comment]
Hi!

As I can see, suggested city is working fine: https://gyazo.com/d456af47b585d70298f0fc902979949c
Could you please specify the question? Thanks!

**Comment by plplmax** [comment]
Oh, I get it. When you click on the suggested city using the touchpad, it doesn't work, but when you press the left mouse button, it works fine :)

**Comment by tpsupport** [comment]
We're glad, that the issue is solved.
Feel free to contact us by email support@travelpayouts.com

**Comment by plplmax** [comment]
The issue hasn't been solved, if I may say so. One click with the touchpad doesn't work, two quick clicks work. Correct me if I'm wrong.

**Comment by tpsupport** [comment]
We've tested it, and it works with one touch in on the touchpad: https://gyazo.com/b47a4a71c55814611f39eed7799eef5c
Same thing on the mobile devices.

It actually depends on the settings of your device — touch could or could not represent as action. 

Feel free to ask any questions.
