### ISSUE TITLE
Problem with installation.

### ISSUE THREAD

**Issue by koziejakub** [travelpayouts/flights-api-project#8]
Follow the instructions to install this. Unfortunately, when I upload to the server I get a bug that looks like I forgot to compile the files - follow the instructions and still does not work. How do I solve this?

**Comment by Klimtrav** [comment]
Hi i have problem with Stylesheet style.css.

**Comment by tpsupport** [comment]
> Hi i have problem with Stylesheet style.css.

Hi! Could you please be more specific about the issue?

**Comment by Klimtrav** [comment]
I have try to install on WordPress, but didn‘t work.
Stylesheet style.css is missing

**Comment by tpsupport** [comment]
Could you please send us the details about the issue (link to your website, screenshots, the example of the CSS codes) at the email address support@travelpayouts.com? We will be glad to help.

Thank you.

**Comment by koziejakub** [comment]
First, template is not for Wordpress.

śr., 2 mar 2022, 13:19 użytkownik Klimtrav ***@***.***>
napisał:

**Comment by tpsupport** [comment]
The Travelpayouts Travel App for Android and iOS  is an app template for flights and hotels search. As for WordPress, we have our own plugin for it: https://wordpress.org/plugins/travelpayouts/

If you have any questions, please write to support@travelpayouts.com.

**Comment by Klimtrav** [comment]
<img width="1214" alt="Bildschirmfoto 2022-03-03 um 10 50 53" src="https://user-images.githubusercontent.com/100771823/156540414-32e66e40-d9c2-45a9-9a63-48959c483d98.png">

**Comment by Klimtrav** [comment]
sorry it is in german language

**Comment by tpsupport** [comment]
Could you please clarify what kind of theme you want to install, where did you get this file from?

**Comment by Klimtrav** [comment]
https://github.com/travelpayouts/flights-api-project

**Comment by tpsupport** [comment]
Thanks for the clarification! This is a pretty old project, which is currently not supported, it is not a Wordpress theme. It needs to be uploaded to your ftp server, but not a WordPress site. In addition, access to the search API is required to use it.

We recommend that you have a look at our White Label product: http://www.travelpayouts.com/promo/whitelabel/en/index.html

White Label is a search powered by Aviasales and Hotellook that is integrated into your website's design. If you have White Label, users will view search results on a subdomain of your website. Without White Label, users are redirected to [Aviasales.com](https://www.aviasales.com/) or [Hotellook.com](https://hotellook.com/) when performing a search.


It's an easier and faster way to create your own search than using API.
